# ¿Cuando hubo más gente en cuarentena desde marzo del 2020 por región?

In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#df = pd.read_csv('C:/Users/camil/Desktop/UDD/Análisis de Datos/Tarea 1/CasosNuevosCumulativo.csv'
#                   ,index_col ='Region')
df = pd.read_csv('https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto13/CasosNuevosCumulativo.csv?raw=true', sep=',')

In [11]:
df

,Region,2020-03-03,2020-03-04,2020-03-05,2020-03-06,2020-03-07,2020-03-08,2020-03-09,2020-03-10,2020-03-11,...,2021-10-03,2021-10-04,2021-10-05,2021-10-06,2021-10-07,2021-10-08,2021-10-09,2021-10-10,2021-10-11,2021-10-12
0,Arica y Parinacota,0,0,0,0,0,0,0,0,0,...,28,18,8,20,22,21,15,27,11,13
1,Tarapacá,0,0,0,0,0,0,0,0,0,...,23,41,31,17,47,18,42,17,36,22
2,Antofagasta,0,0,0,0,0,0,0,0,0,...,30,51,28,33,42,32,35,38,36,37
3,Atacama,0,0,0,0,0,0,0,0,0,...,23,15,9,10,10,10,15,17,15,5
4,Coquimbo,0,0,0,0,0,0,0,0,0,...,27,25,14,34,18,25,37,38,29,11
5,Valparaíso,0,0,0,0,0,0,0,0,0,...,79,41,34,42,89,84,88,93,73,40
6,Metropolitana,0,1,1,1,1,2,3,1,4,...,364,341,266,414,556,624,583,626,568,343
7,O’Higgins,0,0,0,0,0,0,0,0,0,...,25,21,27,24,25,36,48,18,28,31
8,Maule,0,1,0,0,0,1,1,1,2,...,33,28,16,43,29,52,44,76,59,44
9,Ñuble,0,0,0,0,0,0,0,0,0,...,13,17,6,8,18,11,14,28,25,16
10,Biobío,0,0,0,0,0,0,1,0,0,...,44,27,30,39,44,43,39,49,60,32
11,Araucanía,0,0,0,0,0,0,0,0,0,...,30,28,18,10,27,23,18,19,17,18
12,Los Ríos,0,0,0,0,0,0,0,0,0,...,11,5,1,8,17,14,16,19,12,6
13,Los Lagos,0,0,0,0,1,0,0,0,0,...,18,9,11,7,28,40,33,27,20,15
14,Aysén,0,0,0,0,0,0,0,0,0,...,3,6,3,5,8,4,6,13,6,1
15,Magallanes,0,0,0,0,0,0,0,0,0,...,1,0,1,0,1,0,0,0,1,0
16,Total,0,2,1,1,2,3,5,2,6,...,752,673,503,714,981,1037,1033,1105,996,634

In [4]:
print(df.columns)
print(df.shape)
print(df.head(5))
print(df.index.name)

Index(['Region', '2020-03-03', '2020-03-04', '2020-03-05', '2020-03-06',
       '2020-03-07', '2020-03-08', '2020-03-09', '2020-03-10', '2020-03-11',
       ...
       '2021-10-03', '2021-10-04', '2021-10-05', '2021-10-06', '2021-10-07',
       '2021-10-08', '2021-10-09', '2021-10-10', '2021-10-11', '2021-10-12'],
      dtype='object', length=590)
(17, 590)
               Region  2020-03-03  2020-03-04  2020-03-05  2020-03-06  \
0  Arica y Parinacota           0           0           0           0
1            Tarapacá           0           0           0           0
2         Antofagasta           0           0           0           0
3             Atacama           0           0           0           0
4            Coquimbo           0           0           0           0

   2020-03-07  2020-03-08  2020-03-09  2020-03-10  2020-03-11  ...  \
0           0           0           0           0           0  ...
1           0           0           0           0           0  ...
2           0           0           0           0           0  ...
3           0           0           0           0           0  ...
4           0           0           0           0           0  ...

   2021-10-03  2021-10-04  2021-10-05  2021-10-06  2021-10-07  2021-10-08  \
0          28          18           8          20          22          21
1          23          41          31          17          47          18
2          30          51          28          33          42          32
3          23          15           9          10          10          10
4          27          25          14          34          18          25

   2021-10-09  2021-10-10  2021-10-11  2021-10-12
0          15          27          11          13
1          42          17          36          22
2          35          38          36          37
3          15          17          15           5
4          37          38          29          11

[5 rows x 590 columns]
None

In [5]:
dfd = df.iloc[:,1:588]
print(dfd.columns)

Index(['2020-03-03', '2020-03-04', '2020-03-05', '2020-03-06', '2020-03-07',
       '2020-03-08', '2020-03-09', '2020-03-10', '2020-03-11', '2020-03-12',
       ...
       '2021-10-01', '2021-10-02', '2021-10-03', '2021-10-04', '2021-10-05',
       '2021-10-06', '2021-10-07', '2021-10-08', '2021-10-09', '2021-10-10'],
      dtype='object', length=587)

In [6]:
dfd.columns = pd.to_datetime(dfd.columns).strftime("%Y/%m/%d")
print(dfd.head(5))

   2020/03/03  2020/03/04  2020/03/05  2020/03/06  2020/03/07  2020/03/08  \
0           0           0           0           0           0           0
1           0           0           0           0           0           0
2           0           0           0           0           0           0
3           0           0           0           0           0           0
4           0           0           0           0           0           0

   2020/03/09  2020/03/10  2020/03/11  2020/03/12  ...  2021/10/01  \
0           0           0           0           0  ...          32
1           0           0           0           0  ...          36
2           0           0           0           0  ...          37
3           0           0           0           0  ...          17
4           0           0           0           0  ...          26

   2021/10/02  2021/10/03  2021/10/04  2021/10/05  2021/10/06  2021/10/07  \
0          50          28          18           8          20          22
1          21          23          41          31          17          47
2          65          30          51          28          33          42
3          12          23          15           9          10          10
4          28          27          25          14          34          18

   2021/10/08  2021/10/09  2021/10/10
0          21          15          27
1          18          42          17
2          32          35          38
3          10          15          17
4          25          37          38

[5 rows x 587 columns]

In [7]:
dfp = dfd.groupby(pd.PeriodIndex(dfd.columns, freq="d"), axis=1).sum()
print(dfp.head(5))

   2020-03-03  2020-03-04  2020-03-05  2020-03-06  2020-03-07  2020-03-08  \
0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0

   2020-03-09  2020-03-10  2020-03-11  2020-03-12  ...  2021-10-01  \
0         0.0         0.0         0.0         0.0  ...        32.0
1         0.0         0.0         0.0         0.0  ...        36.0
2         0.0         0.0         0.0         0.0  ...        37.0
3         0.0         0.0         0.0         0.0  ...        17.0
4         0.0         0.0         0.0         0.0  ...        26.0

   2021-10-02  2021-10-03  2021-10-04  2021-10-05  2021-10-06  2021-10-07  \
0        50.0        28.0        18.0         8.0        20.0        22.0
1        21.0        23.0        41.0        31.0        17.0        47.0
2        65.0        30.0        51.0        28.0        33.0        42.0
3        12.0        23.0        15.0         9.0        10.0        10.0
4        28.0        27.0        25.0        14.0        34.0        18.0

   2021-10-08  2021-10-09  2021-10-10
0        21.0        15.0        27.0
1        18.0        42.0        17.0
2        32.0        35.0        38.0
3        10.0        15.0        17.0
4        25.0        37.0        38.0

[5 rows x 587 columns]

In [25]:
sum_monthly = dfp.sum(axis=0)
print(sum_monthly)

2020-03-03       0.0
2020-03-04       4.0
2020-03-05       2.0
2020-03-06       2.0
2020-03-07       4.0
               ...
2021-10-06    1428.0
2021-10-07    1962.0
2021-10-08    2074.0
2021-10-09    2066.0
2021-10-10    2210.0
Freq: D, Length: 587, dtype: float64

In [27]:
sort_monthly = sum_monthly.sort_values(ascending=False)/2
sort_monthly

2021-04-09    9171.0
2021-06-05    8867.0
2021-05-28    8680.0
2021-05-29    8426.0
2021-06-04    8273.0
               ...
2020-03-07       2.0
2020-03-10       2.0
2020-03-05       1.0
2020-03-06       1.0
2020-03-03       0.0
Freq: D, Length: 587, dtype: float64